### ISSUE TITLE
Loki Tokens Not Recieved in Wallet

### ISSUE THREAD

**Issue by superdevo333** [loki-project/loki-electron-gui-wallet#106]
Hello, I just initiated a transfer of Loki Tokens from Kucoin to my Loki  Electron Wallet.  Kucoin says the transaction was completed on their end....but it has been over 24 hours and I have yet to receive it in my wallet.  

Would you please help me with this or let me know where I can find support for the Loki Electron Wallet?

Thanks, Sirian

**Comment by Skelaton4** [comment]
Make sure you are one 1.3.1 wallet version

**Comment by superdevo333** [comment]
Yes I am on version 1.3.1.

**Comment by KeeJef** [comment]
Try connecting to a remote node and rescanning your wallet

**Comment by superdevo333** [comment]
I am new to all this....I just wanted to own some Loki tokens & thought it would be easy...lol  How does one connect to a remote node and re-scan?

**Comment by Skelaton4** [comment]
![image](https://user-images.githubusercontent.com/28955674/69187178-163cdf80-0ae8-11ea-8e8e-24c1a6805118.png)

**Comment by superdevo333** [comment]
Ok, so this was the remote node that worked:  https://www.screencast.com/t/8SCvEVXbAD9

The wallet is says it is "SCANNING" in bottom left corner, but I am unable to select the "Rescan Wallet" menu option from the "SETTINGS" dropdown menu in the top right (actually all options in that menu are disabled and show a red cross out sign when I hover over them):  https://www.screencast.com/t/BpYTu6hxBX4

**Comment by Skelaton4** [comment]
You need to let it finish scanning, once you are at 100% you will be able to see your wallet and tokens.

**Comment by superdevo333** [comment]
Ok...so  how will I know it is done scanning?  Is it the following percentage in the bottom right corner of the wallet https://www.screencast.com/t/CtI606ta74ud ?

**Comment by Mikunj** [comment]
Yep, the percentage on the bottom right shows the current progress. Has this issue been resolved on the latest wallet version?
