### ISSUE TITLE
Cann't switch wallets

### ISSUE THREAD

**Issue by RastoSi** [loki-project/loki-electron-gui-wallet#114]
Hi team, I have 4 wallet addresses configured in Loki electron Wallet v 1.3.2.
I logged into one wallet, sent loki, then I try to switch to other wallet but I am getting error - "Cannot connect to wallet-rpc" (even when I enter incorrect password). After GUI wallet restart it works ok but again I can only use 1 wallet, then need to restart GUI.

Regards,
Rasto

**Comment by Mikunj** [comment]
Thanks for the report, i'll look into this issue :)

**Comment by Mikunj** [comment]
This should be fixed in the new wallet

**Comment by RastoSi** [comment]
Thanks,
RastoS
