### ISSUE TITLE
Wallet Sync height 442000

### ISSUE THREAD

**Issue by Azazel020** [loki-project/loki-electron-gui-wallet#116]
**Describe the bug**

When I open my Electron wallet the wallet starts syncing from block 442000. It doesn`t start where it ended since the last sync.

**To Reproduce**
 1) Open the wallet (remote node only)
 2) Check right corner below 

**Screenshots or Log files**
See attachment
![2020-01-29 08_24_17-](https://user-images.githubusercontent.com/44430967/73336016-01f82a00-4271-11ea-8d8c-7f9672f72a0e.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of Wallet : 1.3.3

**Comment by Azazel020** [comment]
I use several wallets and in most of the cases it is block 442.000 but also see other numbers. Main problem.: It doesn`t continue from the block since latest sync

**Comment by Azazel020** [comment]
It only happens when you use a remote node.

**Comment by Mikunj** [comment]
Please comment on this issue if this is still happening. For now i will close this.
