### ISSUE TITLE
Correctly show staking and unlocking transaction labels.

### ISSUE THREAD

**Issue by Azazel020** [loki-project/loki-electron-gui-wallet#117]
**Describe the bug**
After unlocking a SN there is a transaction in your wallet with transaction type: FAILED, after x conformations it changes to SENT
Same for registering a SN, after x conformations it also changes to SENT

Is it possible to change the label for both transactions?

Unlock node
Register node

**To Reproduce**

Open the wallet
Unlock a SN 
Check transactions

**Screenshots or Log files**
See attachment, don`t have any unlock now so can`t show the failed status
![2020-01-29 08_31_10-Loki Electron Wallet v1 3 3](https://user-images.githubusercontent.com/44430967/73336618-931bd080-4272-11ea-8896-3b9c470accbb.jpg)

**Desktop (please complete the following information):**
 - OS: Window 10
 - Version of Wallet: 1.3.3

**Comment by LokiNugget** [comment]
<img width="213" alt="Screen Shot 2020-07-16 at 11 28 38 pm" src="https://user-images.githubusercontent.com/64828760/87676580-1fd42f80-c7bc-11ea-9e3f-379136c0dc66.png">

Happens to me also when I unlock SN's via the Electron GUI. Eventually (weeks/months) they change to "Sent"

Any updates on this bug?

**Comment by Mikunj** [comment]
I'll be looking into this soon and fixing it up if I can.

**Comment by kylezs** [comment]
This will be fixed in 1.5.0.
