### ISSUE TITLE
Auto updating on Mac is broken.

### ISSUE THREAD

**Issue by Mikunj** [loki-project/loki-electron-gui-wallet#124]
Auto updating on Mac requires a `zip` file.
See: https://github.com/electron-userland/electron-builder/issues/2199

The problem is when we make this zip file, it is corrupted for some reason.
See:
https://github.com/electron-userland/electron-builder/issues/4299

We need to fix this before auto updating on mac will work :(

**Comment by thomasdarde** [comment]
Did you try the solution provided here ? 
https://github.com/electron-userland/electron-builder/issues/4299#issuecomment-541249788

**Comment by Mikunj** [comment]
I'm going to try a few things today. My suspicious is that we can still build the zip and it will still work correctly in auto-updating, but manually downloading from chrome and unzipping it will corrupt it. I tried a test yesterday where i downloaded a binary built with electron-builder on chrome and safari. To my surprise the one downloaded and extracted from safari worked fine.

**Comment by Mikunj** [comment]
Update: If you unzip the file using another program (Not the default Archive Utility), it works fine. I have tested that it also works as intended for auto-updating.
