### ISSUE TITLE
Setup was not completed successfully

### ISSUE THREAD

**Issue by sambrown05** [loki-project/loki-electron-gui-wallet#125]
After clicking a fake update link and going into damage control, I am now attempting to reinstall this app. Unfortunately I can't get past this issue. Any ideas?
![image](https://user-images.githubusercontent.com/61309786/75855525-347fde80-5e3e-11ea-9370-f66d9a01d374.png)

**Comment by Mikunj** [comment]
Thanks for the report, have you tried running the setup as an Administrator? You can just `Right Click -> Run as Administrator` and see if that works.

**Comment by sambrown05** [comment]
Yes, I've tried all combinations of that and single/all user install

**Comment by Mikunj** [comment]
I will look into this further
