### ISSUE TITLE
Importing old GUI wallets failing

### ISSUE THREAD

**Issue by Mikunj** [loki-project/loki-electron-gui-wallet#131]
From Telegram:

```
Mr Aka, [8 Apr 2020 at 12:33:20 am]:
I stopped using loki for 2 years ad now i am confused

there is a new wallet, and it has option to restore from old GUI But after checking the ox nothing happens

i got alloacted some loki during the pre ICO

can somedy help?

And when I impot from file, a red traingle pops up and then nothing
```

**Comment by rackam74** [comment]
I have the same problem i can't restore my old wallet from the file and from the 21 words..... did you resolve the issue??

**Comment by Mikunj** [comment]
> I have the same problem i can't restore my old wallet from the file and from the 21 words..... did you resolve the issue??

Hey, I couldn't seem to find the cause of the issue. You can try do the process manually.
1. Go to the location of your wallet.
2. Find the wallet you want to restore. It should be in a folder with your wallet name.
3. Move all files inside the folder to the parent folder.

**Comment by rackam74** [comment]
Thank a lot !! it works!!!
