### ISSUE TITLE
Unlocking SN from GUI says FAILED, however SN tab reports correct Unlock Height

### ISSUE THREAD

**Issue by yidakee** [loki-project/loki-electron-gui-wallet#134]
Can't really try to replicate as I don't want to unlock another node, but I can say the wallet was open for over 24h, I forgot to close it down. However idle, perfectly up to height.

Went into Service Node tab, and unlocked 3 nodes. Transaction went through after long block time (around 8 minutes). LokiSNBot faithfully warned me. However, the wallet shows the tx failed 

<img width="1271" alt="Screenshot 2020-05-16 at 12 11 55" src="https://user-images.githubusercontent.com/16577836/82118394-15bb9380-976f-11ea-8211-5e7bc33746da.png">

If I go into the Service Node tab, each node is reporting the "Unlocking at height xxxxxx" correctly. Restarting the wallet does not fix it.

**Comment by Mikunj** [comment]
Possibly related to #117
going to close this for now.
