### ISSUE TITLE
restore wallet

### ISSUE THREAD

**Issue by Lokimember** [loki-project/loki-electron-gui-wallet#137]
I have restore (old computer crashed) my wallet from the seed in "loki-electron-wallet-1.4.3-win". But i have 0 Loki balance. What to do?

**Comment by Skelaton4** [comment]
Did you set the restore height to 0.

**Comment by Mikunj** [comment]
Please comment on this issue if the suggestion above did not solve the issue. For now i will close this.

**Comment by Lokimember** [comment]
The problem is solved.
