### ISSUE TITLE
Add "rescan spent" menu option

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki-electron-gui-wallet#142]
Sometimes a rescan_spent can solve spending issues when the wallet has, for some reason, missed that some inputs are spent.  This can sometimes solve issues without a more drastic full blockchain rescan.  (In theory this shouldn't happen, in practice sometimes it does).  The wallet RPC API call to "rescan_spent" is simple -- it takes no arguments, and the rescan occurs very fast.

**Comment by Mikunj** [comment]
There is an option to rescan spent outputs already. When you go Menu > Rescan wallet, you are given the option to choose between full blockchain or spent outputs
