### ISSUE TITLE
Add check for the right file type when importing wallet.

### ISSUE THREAD

**Issue by Sonofotis** [loki-project/loki-electron-gui-wallet#15]
Javascript error pops up when importing a wrong key file and the wallet freezes.

Add check for the right file type before trying to import file.

OS: Windows
Release: v1.1.0

**Comment by Mikunj** [comment]
Hey could you provide screenshots and quick example on how to reproduce the error?

**Comment by Sonofotis** [comment]
Open GUI on windows >
"Import wallet from file" >
"SELECT WALLET FILE" >
"Enter Wallet Name" >
Choose Random file, such as pdf, jpg, e.t.c >
Following error pops up:
![new wallet gui error](https://user-images.githubusercontent.com/39609800/55052276-6d4ef980-50ac-11e9-92fb-171fc34a340d.JPG)

**Comment by Mikunj** [comment]
👍 cheers

**Comment by Sonofotis** [comment]
Error not occurring now that my GUI has a wallet already in there.

Try it with a new install.

**Comment by Mikunj** [comment]
I've fixed it locally and it will show a nice error now. However you got this error because the wallet that you were trying to import is probably open/in-use somewhere else.

**Comment by Sonofotis** [comment]
Interesting, Was not in use anywhere else.

The error first did generate from importing the wallet made in the cli.
