### ISSUE TITLE
Windows: Failed to save file "C:\Users\Username\Documents\Loki\wallets/Wallet.keys"

### ISSUE THREAD

**Issue by Sonofotis** [loki-project/loki-electron-gui-wallet#17]
Windows Gui fails to save key files as it's using a forward slash instead of a back slash for the filepath.

**Comment by Mikunj** [comment]
When does this occur? When restoring or creating?

**Comment by Sonofotis** [comment]
When creating a new wallet

**Comment by Mikunj** [comment]
Closing this as i might have fixed it
