### ISSUE TITLE
Wallet imported from old gui with no password can't be deleted. Error: INVALID PASSWORD

### ISSUE THREAD

**Issue by Sonofotis** [loki-project/loki-electron-gui-wallet#18]
OS: Windows
Version 1.1.0

Flow:
Import Wallet from old Gui. >
Asks for password, enter no password and click enter. >
Click settings >
Delete Wallet> 
Delete>
Type no password >
Delete >
outputs "invalid password"

**Comment by Mikunj** [comment]
Can you confirm if this is happening to all old gui wallets and not a specific one? I can't seem to be able to reproduce this :(
