### ISSUE TITLE
Electron GUI 1.4.5 - Bug with "Send All" - macOS 

### ISSUE THREAD

**Issue by yidakee** [loki-project/loki-electron-gui-wallet#181]
I have replicated a couple of times, including restarting the wallet.

By clicking the "All" button, the pop-up screen shows empty data

<img width="1278" alt="Screenshot 2020-09-15 at 11 47 54" src="https://user-images.githubusercontent.com/16577836/93207537-049d8600-f753-11ea-8052-d8835ff37b7d.png">

Clicking "Send", spinning wheel stayed as long as 15 minutes, before force closing the wallet.

<img width="1279" alt="Screenshot 2020-09-15 at 11 49 54" src="https://user-images.githubusercontent.com/16577836/93207598-1d0da080-f753-11ea-91b4-cc07908b443d.png">

Tested with manually inputting amount, seems fine

<img width="1279" alt="Screenshot 2020-09-15 at 11 57 13" src="https://user-images.githubusercontent.com/16577836/93207657-2e56ad00-f753-11ea-9bcb-ebcb1e63df90.png">

Clicked cancel and tried all again, as you see pop-up remembers previous manual input of 100, not the All amount

<img width="1279" alt="Screenshot 2020-09-15 at 11 57 44" src="https://user-images.githubusercontent.com/16577836/93207704-44646d80-f753-11ea-8d12-32c3495ad57c.png">

Clicked Cancel and tried another manual input, seems ok

<img width="1279" alt="Screenshot 2020-09-15 at 11 59 07" src="https://user-images.githubusercontent.com/16577836/93207726-4a5a4e80-f753-11ea-84b0-07fe8555d820.png">

Tried "All" again, pop-up remembers previous manual input

<img width="1277" alt="Screenshot 2020-09-15 at 11 59 53" src="https://user-images.githubusercontent.com/16577836/93207788-652cc300-f753-11ea-8656-db08a615e76d.png">

Clicked cancel, entered a manual input, and sent without issues.

**Comment by kylezs** [comment]
Hi @yidakee ,

Thanks for the report and detailed reproduction steps, I will look into it.

**Comment by kylezs** [comment]
Hi @yidakee, I have had a look into it and was able to reproduce on my end. Would you be able to validate the fix (there are a few other fixes included), using a dev build found here:
https://github.com/loki-project/loki-electron-gui-wallet/actions/runs/256777451

**Comment by yidakee** [comment]
@kylezs - Now when I select "All" I get the red "insufficient funds" pop-up

**Comment by kylezs** [comment]
@yidakee Thanks for testing that out. This will be due to the fee, since "send" will attempt to send the full amount entered, implying the fee is taken from the wallet, and not inclusive of the send amount. I guess that could be made clearer, or resolved some other way... If you remove 1 LOKI from the `ALL` amount, is it working fine?

**Comment by yidakee** [comment]
@kylezs - That is correct, leaving enough for fees does work. I agree this it can be a little misleading. I expected it to work just like `sweep_all`

**Comment by kylezs** [comment]
Sending "ALL" will now use the `sweep_all` RPC call. When not using subaddresses this will work as expected, sending all minus the fee (so 0 funds left in wallet). 

When using subaddresses `sweep_all` will select a single random subaddress with unspent outputs and send the funds from that subaddress to the target address.
This means when sending all (or sweeping all) and using subaddresses you are not actually sending (or sweeping) *all*. This is to be resolved after next HF with the inclusion of a new flag to sweep all addresses.
