### ISSUE TITLE
Cannot unlock node

### ISSUE THREAD

**Issue by 0x00031337** [loki-project/loki-electron-gui-wallet#26]
In the "service node" tab is the "unlock" button. Pressing it should cause to request the release of funds locked in the Service Node. Unfortunately, it does not work. The command is not sent, an error appears in the application - a message highlighted in red. Tested on testnet blockchain.

**Comment by Mikunj** [comment]
Hey, what error appears in the application?

**Comment by 0x00031337** [comment]
Just "Unlocking..." on a red background. No transaction in blockchain.
> Version: ATOM v1.1.1-v0.3.2.0
Under the CLI wallet everything works ok. A blockchain transaction is being broadcast.

**Comment by Mikunj** [comment]
Cool, i'll look into it 👍
