### ISSUE TITLE
Loki Atom Wallet V 1.1.2

### ISSUE THREAD

**Issue by luisitoloki** [loki-project/loki-electron-gui-wallet#36]
Having a problem with the new version of Loki Atom Wallet V 1.1.2

Action done:
- Uninstall and install (5 times).
- Desactivate Anti-Virus & Windows Defender.
- Wallet sync ok. Log out, but can't log in. Message = Fail to open wallet.
- Some times show balance 0 coins.

Using same seed & password on GUI Wallet V.3.0.2. 
- Log in and log out with no problem.
- Balance is correct. Verified with CLI wallet.
- Crash frequently.

**Comment by Mikunj** [comment]
Hey thanks for the report, could you check if your wallet opens fine in v1.1.1?

**Comment by luisitoloki** [comment]
No. I tried. Same problem

**Comment by OlderNews** [comment]
Version 1.1.2 Issue On first time setup. I've had the same problem on multiple Windows computers each time installing to the Electron wallet from the Classic Gui and version 1.1.1
 First time setting up takes a lot longer to Connect to Daemon on Windows. 
- Generally takes 5-10 minutes of waiting for GUI to connect to Daemon. 
- It would be good to know why it takes so long for the Daemon to connect the first time. 
- Is it Reorganising blocks?
- After the 5-10 minutes, Antivirus flags rpc.exe. Once allowed wallet works after a minute or two. 
- Please have a first time warning for noobs, or further information while waiting for connection.

**Comment by OlderNews** [comment]
GUI request
Once logged and sending transaction: 
Please change the optional notes to - 
FROM: Additional notes to attach to the transaction
TO: Additional notes to locally attach to the transaction 

This may help people understand why their comments may not transfer to other wallets.

**Comment by luisitoloki** [comment]
Update......

Still having the same problem..... but this weekend I created another wallet on V1.1.2. I could log in & out with no problem.
I don't know if my original wallet could be corrupted?
Also, my coins should be unlocked by now and they are still locked.
Thanks!!!

**Comment by Mikunj** [comment]
> Update......
> 
> Still having the same problem..... but this weekend I created another wallet on V1.1.2. I could log in & out with no problem.
> I don't know if my original wallet could be corrupted?
> Also, my coins should be unlocked by now and they are still locked.
> Thanks!!!

Could be. Maybe try restore that wallet? You can do it by going to the wallet directory and deleting the wallet files, and then restoring by seed from the gui. Or if you don't want to delete then you can restore it with a different wallet name.

**Comment by luisitoloki** [comment]
I already did that... deleted all files... installed all over again and use seed. Still having the same issues

**Comment by luisitoloki** [comment]
Also, forgot to mention that every time I want to log in V3.0.2 says (Electrum seed is empty). To have access I need to use my seed from my USB.

**Comment by Mikunj** [comment]
@luisitoloki are you still having issues on v1.3.3 version of the wallet?
