### ISSUE TITLE
GUI Daemon Syncing issues

### ISSUE THREAD

**Issue by OlderNews** [loki-project/loki-electron-gui-wallet#38]
Version 1.1.2 Issue On first time setup. I've had the same problem on multiple Windows computers each time installing to the Electron wallet from the Classic Gui and version 1.1.1
First time setting up takes a lot longer to Connect to Daemon on Windows.

Generally takes 5-10 minutes of waiting for GUI to connect to Daemon.
It would be good to know why it takes so long for the Daemon to connect the first time.
Is it Reorganising blocks?
After the 5-10 minutes, Antivirus flags rpc.exe. Once allowed wallet works after a minute or two.
Please have a first time warning for noobs, or further information while waiting for connection.

**Comment by Mikunj** [comment]
Not sure if this issue still occurs, so i'm going to close it. If it does happen we can create a new issue.
