### ISSUE TITLE
GUI - Staking Improvement Request 

### ISSUE THREAD

**Issue by OlderNews** [loki-project/loki-electron-gui-wallet#40]
1. After you Stake to a Service node in a pool using the GUI, it deletes your own wallet address. This makes you re-enter your wallet address each time you want to stake to a Service node pool.

2. It would be good if there was a list of Service Nodes you have contributed to stored separately in the Service Node Section so people can quickly disable Service Node Infinite staking.

**Comment by jagerman** [comment]
Closely related to this is https://github.com/loki-project/loki/issues/563 - since the only address you can actually put in there is your own address, the address field should just be scrapped entirely.
