### ISSUE TITLE
Add progress bar blockchain sync

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-electron-gui-wallet#45]
Seems that this was reported on telegram. 

But when the User has partially downloaded the blockchain already, and they start the Electron GUI wallet, the Wallet will scan through their already downloaded blockchain. This leaves the Wallet stuck at the "Starting daemon" screen. 

A meaningful progress bar should be added so that the user knows that the daemon is not stuck and is indeed scanning the old chain

**Comment by Mikunj** [comment]
#38 seems related 👍

**Comment by Mikunj** [comment]
Closing for now since this hasn't been reported again.
