### ISSUE TITLE
Improve Sweep All user flow

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-electron-gui-wallet#50]
Often a user will need to sweep all before they stake. Its somewhat unclear to new users how to do this in the GUI wallet. @jagerman made these suggestions.

> Actually all is probably fine.  Maybe there could be a "sweep all" button on the staking page--it would do the same thing as "All" on the send page sent to yourself, but provides a shortcut. even better: intercept that error message and put up some popup "Your wallet contains too many transactions to submit this stake.  You will have to "sweep" the require funds back to yourself first.  Do you want to sweep now?" with "Yes" -> prefilled Send page.

**Comment by Sonofotis** [comment]
Bump! This is important, lots of user's struggling with this error.
