### ISSUE TITLE
Linux AppImage Issue (Manjaro KDE)

### ISSUE THREAD

**Issue by treepi3** [loki-project/loki-electron-gui-wallet#51]
Hi, I've noticed when opening the appimage file it asks to "integrate and run". It runs fine, however, the integration is broken (adding icon to launcher etc). When trying to launch from the launcher it gives the error /user/Loki not found. So, it seems to be mishandling one of the data directory's when setting up the .desktop file (thats what I'm assuming). 

It should be a pretty simple fix as long as it's easy to find the bit of code that creates the .desktop file right?

**Comment by Mikunj** [comment]
Hmm, i looked into this and it might be a problem with `electron-builder` itself. I can upload other linux formats such as `snap` and `deb` if that would help.

**Comment by treepi3** [comment]
> Hmm, i looked into this and it might be a problem with `electron-builder` itself. I can upload other linux formats such as `snap` and `deb` if that would help.

It's not a big deal. I got it working by just using the menu editor to edit the .desktop file itself. Very minor issue that I just thought I'd share. No need to upload other formats. That's just more of a hassle. However, I just posted a new issue about the GUI and electron wallets you might want to check out.
