### ISSUE TITLE
Stake all function pointless

### ISSUE THREAD

**Issue by OlderNews** [loki-project/loki-electron-gui-wallet#53]
When Staking to a Service node using the GUI, it asks.

- Public key
- Address
- Amount

Under amount: it gives you the option to stake all, this option seems pointless if you have more then the staking amount required. If the pool requires 10,000 Loki and you have 11,000 Loki, the Stake all function will enter the amount 11,000 Loki. 

Stake all should be stake all of what is required, not stake all of what you have. 

Just a little UI improvement. Thanks

**Comment by Mikunj** [comment]
🤔 The problem with this is that we have no way of knowing how much loki is needed to stake, thus the all button just adds in all of the unlocked user balance
