### ISSUE TITLE
Need help finding my lost transaction on the new wallet (v1.1.3)

### ISSUE THREAD

**Issue by gabayim** [loki-project/loki-electron-gui-wallet#59]
**Describe the bug**
transaction lost although it shows confirmed status in the wallet. there is also no details on the blockchain.

**To Reproduce**
I sent some funds to KuCoin from my private wallet (v1.1.3). 

**Screenshots or Log files**
https://lokiblocks.com/tx/cbc36b0ca059fc16a5edd696708742aa71c5d0c7876a4b9222722697e953d31e

![image](https://user-images.githubusercontent.com/1786273/57969522-d3862900-7945-11e9-95eb-4a83b40075be.png)

**Desktop (please complete the following information):**

 - Version 1.1.3
  -  windows 10

**Comment by gabayim** [comment]
> A clear and concise description of what the bug is.

transaction lost although it shows confirmed status in the wallet. there is also no details on the blockchain.

**Comment by Mikunj** [comment]
Seems re-installing the wallet has resolved this issue for you 👍
