### ISSUE TITLE
Add meaningful progress bar when restoring wallet

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-electron-gui-wallet#6]
Right now we don't show progress for wallets that are restored in the electron GUI, we will need to expose and interpret some more information in the RPC calls to do this.

**Comment by Mikunj** [comment]
https://github.com/loki-project/loki-electron-gui-wallet/blob/master/src-electron/main-process/modules/wallet-rpc.js#L112

The regex there can detect this, but loki wallet rpc doesn't print out height when restoring and thus we never get the update.
