### ISSUE TITLE
Add a warning for Sweep all in Service Node section

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-electron-gui-wallet#65]
When the sweep all button is pressed in the staking section of the wallet, some warning text should show what is about to happen. 

Something like 
"You are about to combine all of your unspent funds by sending a transaction to yourself, your wallet may show a balance of 0 temporarily, after 10 blocks your funds will unlock and you may stake normally"

**Comment by flash25296** [comment]
I am not sure what the wallet is built in but could there not also be tags associated with certain buttons that will show a message when hovered over. Hover over "Sweep All" button describes what is about to happen when you push the button.
