### ISSUE TITLE
Add right click menu 

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-electron-gui-wallet#68]
currently the GUI wallet only allows users to allows users use keyboard shortcuts to copy and paste, we should add a right click menu so users can right click copy and paste

**Comment by Mikunj** [comment]
What elements need this functionality?

**Comment by KeeJef** [comment]
Primarily any field in the send screen which can take an input, also on the service node screen to paste in your SN key. actually we dont really need to have a copy functionality on right click, only really need a paste one since theres buttons beside everything that needs to be copied.
