### ISSUE TITLE
Javascript Error 

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-electron-gui-wallet#69]
**Describe the bug**
An error message appeared when switching wallets, it did not crash the electron application, but when i tried to open another wallet, i was stuck infinitely loading

**To Reproduce**
Not reproducible by me with the same steps, logs maybe useful 

**Screenshots or Log files**
![image](https://user-images.githubusercontent.com/27277414/58845791-e88de680-86bf-11e9-8e7d-4bd05c5a9f52.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version of Wallet or Git commit hash 1.1.4

**Comment by Mikunj** [comment]
This has been fixed in v1.3.3
