### ISSUE TITLE
English language option has an American flag instead of a British flag

### ISSUE THREAD

**Issue by Joshalosh** [loki-project/loki-electron-gui-wallet#70]
**Describe the bug**
The English language option has an American flag. Should be British flag.

**To Reproduce**
Go to the language settings.

**Screenshots or Log files**
<img width="460" alt="Screen Shot 2019-06-05 at 3 47 54 pm" src="https://user-images.githubusercontent.com/13159770/58933392-6f1ef280-87aa-11e9-88ee-c0630eb4f27f.png">

**Desktop (please complete the following information):**
 - macOS Mojave v10.14.4 (not important)
 - Wallet v1.1.4
-  Daemon v3.0.4

**Comment by Sonofotis** [comment]
Put an Australian flag there.

**Comment by Mikunj** [comment]
Would this really need to change? The english translation is marked as `en-us` so marking it with a British(en-uk) or Australian(en-au) flag wouldn't be right.

**Comment by Joshalosh** [comment]
The English flag is the most appropriate to represent the English language.
