### ISSUE TITLE
Mac Closed port crash

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-electron-gui-wallet#74]
**Describe the bug**
on Mac OSX If the RPC port is closed by a firewall, the wallet hangs and throws a runtime error

**To Reproduce**
Run the Wallet on Mac OSX with closed RPC port

**Screenshots or Log files**
![image](https://user-images.githubusercontent.com/27277414/59238759-8c3c4100-8c42-11e9-91f1-b0f73dbab705.png)

**Desktop (please complete the following information):**
 - OS: MAC OSX
 - Version of Wallet or Git commit hash: 1.1.4

**Comment by Mikunj** [comment]
Can't seem to reproduce, need more info.

Remote/Local Daemon? What port? When did the error occur?
