### ISSUE TITLE
Button rendered incorrectly

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-electron-gui-wallet#79]
**Describe the bug**
Button on the show TX details pop up seems to be leaking code

**To Reproduce**

Click on the show tx details button inside the tx

**Screenshots or Log files**
If applicable, add screenshots or Log files to help explain your problem.

![image](https://user-images.githubusercontent.com/27277414/59410169-73c35680-8dfb-11e9-9a67-86a8272e807a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 16.04, Windows 10] Windows 10
 - Version of Wallet or Git commit hash 1.1.4

**Comment by Mikunj** [comment]
This has been fixed already on the development branch.
