### ISSUE TITLE
Service Node Key Copy doesnt Work

### ISSUE THREAD

**Issue by SomethingGettingWrong** [loki-project/loki-electron-gui-wallet#83]
**Describe the bug**
The copy to clipboard function is not working on service node key. After copying its either not copying at all are not updating the windows clipboard. When I tried to paste. It applied the last thing I had copied. 

**To Reproduce**
To reproduce this behavior click on the service node key and copy it
![image](https://user-images.githubusercontent.com/36722911/60064743-efa88300-96c6-11e9-8732-34bd0b229177.png)

**Desktop (please complete the following information):**
Windows 10

**Comment by OlderNews** [comment]
I have the same issue on the Windows 10 version also.
