### ISSUE TITLE
Loki Dashboard is Amazing. Thanks Maxim (enhancement) 

### ISSUE THREAD

**Issue by SomethingGettingWrong** [loki-project/loki-electron-gui-wallet#84]
![image](https://user-images.githubusercontent.com/36722911/60103655-9e7bac00-9725-11e9-843c-a5fcf3ec95d6.png)
![image](https://user-images.githubusercontent.com/36722911/60103665-a3406000-9725-11e9-88ca-43d65be4d505.png)

**These are photo hacks although it would be cool if we could add them** :)

Maybe make src/pages/wallet/lokidashboard.vue Then make a blank iframe template. 
Then add the lokidashboard.com as the source of the iframe. Then src/router/routes.js

Under routerlink

Maybe add <router-link to="/wallet/lokidashboard">

                    <q-btn
                        class="large-btn"
                        :label="$t('buttons.lokidashboard)"
                        size="md"
                        align="left"
                    />
under routes.js 

     {
                path: "lokidashboard",
                component: () =>
                    import("pages/wallet/lokidashboard")
            }

I don't see it taking very long to integrate this.(although in the wallet would be better) I think this would be neat to add really quick and maybe add something to the wallet later.

**Comment by Skelaton4** [comment]
This looks really good.

**Comment by yidakee** [comment]
Wow !! That would be tremendously cool - nice one @SomethingGettingWrong
