### ISSUE TITLE
No start Elektron wallet

### ISSUE THREAD

**Issue by cryptomaxsun** [loki-project/loki-electron-gui-wallet#91]
**Describe the bug**
Such a screen hangs for a long time at startup and nothing happens.

**To Reproduce**

**Screenshots or Log files**
If applicable, add screenshots or Log files to help explain your problem.
https://picua.org/images/2019/07/11/747c55f214eb127b02cc169ed7ef2d14.jpg

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 16.04, Windows 10]
 - Version of Wallet or Git commit hash
Loki Elektron wallet 1.2.1 
Windows 7 x64

**Comment by Mikunj** [comment]
Hmm check to make sure that your anti-virus is not removing the wallet rpc bundled with the electron wallet. That might be why it's hanging specifically on that screen.

**Comment by Mikunj** [comment]
Closed for now
