### ISSUE TITLE
Last Uptime Proof Time/Date in SN details is strange

### ISSUE THREAD

**Issue by Skelaton4** [loki-project/loki-electron-gui-wallet#93]
**Describe the bug**
A clear and concise description of what the bug is. All SN's in the 1.2.2 wallet say the last uptime proof was 1970.

**To Reproduce**
Steps to reproduce the behavior: Look at SN details of any SN

**Screenshots or Log files**
If applicable, add screenshots or Log files to help explain your problem.
![image](https://user-images.githubusercontent.com/28955674/61377254-d7b0c300-a870-11e9-9224-bbd08596d7c4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10]
 - Version of Wallet or Git commit hash : 1.2.2

**Comment by Mikunj** [comment]
Oh good catch, seems like the uptime proof returned by the daemon is in seconds where as js expects it in ms.

**Comment by Mikunj** [comment]
Fixed in f391dc3. It will be out in the next update.
