### ISSUE TITLE
Wallet should confirm tx fee (perhaps for fees about a certain threshold)

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki-electron-gui-wallet#97]
With our fee increase the "Fastest" priority setting has become uselessly large; I received this report from a user who wanted to remain anonymous: he sent a TX, decided to try out the "fastest" fee thinking it might be 5 LOKI or something, then ended up with a 380 LOKI fee TX submitted to the chain with no confirmation or warning:

https://lokiblocks.com/tx/c897572cdcb81d456a87d618195f7fcab4c271cdebd1d907c2f047443dc73582

Now granted the transaction is a bit large (22kB) but even a minimal 2 in/2 out transaction would come out to a 41 LOKI fee.

We really, really need a confirmation of the tx fee before sending, especially for large fees.  Possibly this could use a threshold (e.g. "confirm if the tx fee is above [ 1 ] LOKI" to avoid being too annoying.

Perhaps we should also disable the "Fastest" priority entirely as it seems stupidly high right now as of 4.0.0.

Related: Now that I look at it, I'm not a fan of the labels here either: it is very rare that "Fastest" is actually any faster than "Slow", and I doubt it has *ever* been the case on the Loki chain that Fastest is faster than Normal.

**Comment by jagerman** [comment]
Thinking about this some more, perhaps we should remove the ability to choose the "Fastest" fee entirely: it is *forty* times higher than the "Fast" fee (multipliers relative to "Slow" are: 5 for "Normal", 25 for "Fast", and 1000 for "Fastest").

**Comment by Mikunj** [comment]
Yep i agree, we need to show a confirmation to the user with the txs and fees so that such situation doesn't happen again.

**Comment by kylezs** [comment]
Closed by https://github.com/loki-project/loki-electron-gui-wallet/pull/157
