### ISSUE TITLE
Double Transaction message- Aesthetic Error 

### ISSUE THREAD

**Issue by OlderNews** [loki-project/loki-electron-gui-wallet#99]
Windows GUI- Version 1.2.3-  Windows 10

When Sending a transaction using the GUI.  
**If Success**
Two Green box pop up down the bottom, and claims it was successful. 
**If Fail**
Two red boxes pop up claiming the transaction failed. 

To reproduce- 
Send a transaction, see the notifications down the bottom. 

As the notification comes up 2 times, it may make you think you may have sent two transactions. 
Mildly misleading.

**Comment by Mikunj** [comment]
Thanks for the report, i'll look into it and hopefully fix it by the next release
